<img src="<?= $this->url->get("img/flags/" . $question->image) ?>">

<form action="" method="post">
	<input type="hidden" name="q" value="<?= $question->id ?>">
	<?php foreach($answers as $answer): ?>
		<button type="submit" name="a" value="<?= $answer->id ?>" class="btn-link"><?= $answer->text ?></button>
	<?php endforeach; ?>
</form>

<?php if(isset($lastQuestion)): ?>
	<?php if($lastQuestion->Answers->id == $lastAnswerId): ?>
		Correct
	<?php else: ?>
		Wrong
	<?php endif; ?>
	{% if !$difficulty %}
		, that was <?= $lastQuestion->Answers->text ?>
	{% endif %}

	<p>Score: <?= $score ?> out of <?= $total ?>, <?= $score/$total*100 ?>%</p>
<?php endif; ?>
