<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/css/bootstrap.min.css" integrity="sha384-2hfp1SzUoho7/TsGGGDaFdsuuDL0LX2hnUp6VkX3CUQ2K4K+xjboZdsXyp4oUHZj" crossorigin="anonymous">
		<style>
			body {
				background:
					repeating-linear-gradient(
						-55deg,
						#222,
						#222 10px,
						#292929 10px,
						#292929 20px
					);
				color: #FFF;
			}
			a {
				color: #FFF;
			}
			nav {
				display: flex;
				text-align: center;
			}
			nav a {
				flex-grow: 1;
			}
			img {
				box-shadow: 0 0 1rem 0.1rem #111;
				width: 100%;
			}
			#answers {
				margin: 2.5% 0 0 0;
				display: flex;
				flex-wrap: wrap;
			}
			#answers .padding {
				width: 50%;
			}
			#answers button {
				border: 1px solid #222;
				border-color: #222 #303030 #222;
				text-shadow: 0 1px 0 rgba(0, 0, 0, 0.6);
				background: -webkit-linear-gradient(top, #111, #1C1C1C);
				background: linear-gradient(top, #111, #1C1C1C);
				-pie-background: linear-gradient(top, #111, #1C1C1C);
				color: #eee;
				box-shadow:
					rgba(0, 0, 0, 0.5) 0 0 0.5em,
					rgba(0, 0, 0, 0) 0 0 1px 0,
					rgba(0, 0, 0, 0) 0 0 0 1px inset,
					#555 0 1px 0 0;
				border-radius: 3px;
				margin: 2.5%;
				padding: 2em 0;
				width: 97.5%;
			}
			#answers .padding:first-of-type button, #answers .padding:nth-of-type(3) button {
				margin-left: 0;
			}
			#answers .padding:last-of-type button, #answers .padding:nth-of-type(2) button {
				margin-right: 0;
			}
			#answers .padding:first-of-type button, #answers .padding:nth-of-type(2) button {
				margin-top: 0;
			}
			#answers .padding:last-of-type button, #answers .padding:nth-of-type(3) button {
				margin-bottom: 0;
			}
		</style>
	</head>
	<body>
		<div class="container-fluid">
			<div style="width: 50%; margin: 0 auto;">
				<?= $this->getContent() ?>
			</div>
		</div>

		<!-- Latest compiled and minified JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/js/bootstrap.min.js" integrity="sha384-VjEeINv9OSwtWFLAtmc4JCtEJXXBub00gtSnszmspDLCtC0I4z4nqz7rEFbIZLLU" crossorigin="anonymous"></script>
	</body>
</html>
